# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "workflow-tests" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
    - uses: actions/checkout@v4
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          **/obj/**
          **/bin/**

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Download Build
      uses: actions/download-artifact@v4
      with:
        name: build
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.x
            6.0.x
            3.1.x
    - name: Test .NET 6.0
      run: dotnet test -f net6.0 --no-build --verbosity normal
      continue-on-error: true
    - name: Test .NETCoreApp 3.1
      run: dotnet test -f netcoreapp3.1 --no-build --verbosity normal
      continue-on-error: true
    - name: Setup Mono
      run: |
        sudo apt install ca-certificates gnupg -y
        sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt update -y
        sudo apt install mono-devel -y
    - name: Test .NET Framework 4.7.2 with Mono 5.4
      run: dotnet test -f net472 --no-build --verbosity normal
      continue-on-error: true
